% 20181009 by Dushan N. Wadduwage

function x = recTwIST(y,A,A_waverec2,x0)
    
    A_combined = A;
    A_combined = A*A_waverec2;

    hR = @(x) A_combined*x;
    hRt = @(x) A_combined'*x;
        
    tau = 0;%.6;%.4;%0.01;%0.04;%0.07;% in between 0.001 and 0.0001 for 4&10 um beads
    lambda = 1;%min(eig(A_combined'*A_combined));
    tolA = 1e-6;
    
    [x,x_debias,obj_twist,...
            times_twist,debias_start_twist,mse]= ...
            TwIST(y,hR,tau, ...
            'Lambda', lambda, ...
            'Debias',0,...
            'AT', hRt, ... 
            'Monotone',1,...
            'Sparse', 1,...
            'Initialization',x0,...
            'StopCriterion',1,...
            'ToleranceA',tolA,...
            'Verbose', 1);
  

    x(find(isnan(x)))=0;
    x = A_waverec2*x;
    
end