% 20191123 by Dushan N. Wadduwage (wadduwage@fas.harvard.edu)
% 20200429 modified by Dushan N. Wadduwage (wadduwage@fas.harvard.edu)
% 20200629 modified by Dushan N. Wadduwage (wadduwage@fas.harvard.edu)

function net = tr_net_dirct(lgraph,X,Y,pram)

    X_tr  = X(:,:,:,1:end-pram.miniBatchSize);
    X_val = X(:,:,:,end-pram.miniBatchSize+1:end);
    Y_tr  = Y(:,:,:,1:end-pram.miniBatchSize);
    Y_val = Y(:,:,:,end-pram.miniBatchSize+1:end);
    
    Ngpus = 2;
    N_tr  = floor(size(X_tr,4)/(Ngpus*pram.miniBatchSize))*Ngpus*pram.miniBatchSize;
    X_tr  = X_tr(:,:,:,1:N_tr);
    Y_tr  = Y_tr(:,:,:,1:N_tr);

    %% train network
    l2reg = 0.0001;
    options = trainingOptions('sgdm', ...
        'ValidationData', {X_val,Y_val}, ...
        'Momentum',0.9, ...
        'InitialLearnRate',pram.learnRateImgprocessor, ...
        'LearnRateSchedule','piecewise', ...
        'LearnRateDropPeriod',pram.learnRateDropInterval, ...
        'LearnRateDropFactor',pram.learnRateDropFactor, ...
        'L2Regularization',l2reg, ...
        'MaxEpochs',pram.numEpochs ,...        
        'ValidationFrequency', 50, ...
        'MiniBatchSize',pram.miniBatchSize, ...
        'GradientThresholdMethod','l2norm', ...
        'Plots','training-progress', ...
        'GradientThreshold',0.01,...
        'ExecutionEnvironment','multi-gpu');                % 'ValidationData',patchds_val,...
        
    net = trainNetwork(X_tr,Y_tr,lgraph,options);
end



